### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by 11138011** [11138011/11138011.github.io#1]
There is some issues on _contact page_ that I couldn't improve or arrange on the form  list that the box and name list cannot match onthe same row so it needs to be lined up [https://11138011.github.io/contact.html](url)

**Comment by jhawlc** [comment]
https://drive.google.com/file/d/1N0e6TlF-Fi_1iAHRQeH2Y9hGO6h5N_6O/view?usp=drive_web&authuser=0

**Comment by jhawlc** [comment]
Try removing the <br> after lables, and ensuring you close the form tag with >

```
<label for="fname">First name:</label>
		<input type="text" id="fname" name="fname" value="">
<br>
		
		<label for="lname">Last name:</label>
		<input type="text" id="lname" name="lname" value="">
<br>
		
		<label for="email">Email Address:</label>
		<input type="text" id="email" name="Email Address" value="">
<br>
```
